import {
  Account,
  BusinessProfile,
  BusinessHour,
  PhoneNumber,
  Contact,
  CallRecord,
  Conversation,
  Message,
  IntakeSession,
  JobCard,
  CannedReply,
  ComplianceRegistration,
  SubscriptionPlan,
  Subscription,
  UsageRecord,
  Notification,
  UserCredential,
} from '@/types';
import { TRADE_TEMPLATES } from '@/lib/trade-templates';
import { hashPasswordSync } from '@/lib/auth/password';


export const SEED_PLANS: SubscriptionPlan[] = [
  {
    id: 'starter',
    name: 'Starter',
    monthly_price_cents: 7900,
    included_calls: 40,
    included_sms: 200,
    included_numbers: 1,
    max_users: 2,
    features: [
      'Missed-call detection (<60s)',
      'Automated SMS text-back',
      'Basic qualification intake',
      'Instant job card creation',
      'Single business phone number',
      'Email & SMS owner notifications',
      'Soft cap overage: $0.35/call',
    ],
  },
  {
    id: 'pro',
    name: 'Pro',
    monthly_price_cents: 14900,
    included_calls: 200,
    included_sms: 1000,
    included_numbers: 2,
    max_users: 5,
    features: [
      'Everything in Starter',
      'Custom trade qualification questions',
      'Photo & media collection',
      'Emergency keyword escalation',
      'Custom canned replies',
      'Daily 6 PM summary & Weekly reports',
      'A2P 10DLC campaign registration support',
      'Soft cap overage: $0.25/call',
    ],
  },
  {
    id: 'business',
    name: 'Business',
    monthly_price_cents: 29900,
    included_calls: 600,
    included_sms: 3000,
    included_numbers: 5,
    max_users: 15,
    features: [
      'Everything in Pro',
      'Multiple phone numbers & rollover routing',
      'Team member assignment & dispatch',
      'Priority telecom deliverability routing',
      'Dedicated compliance manager',
      'Custom webhook exports',
      'Soft cap overage: $0.15/call',
    ],
  },
];

export const SEED_ACCOUNTS: Account[] = [
  {
    id: 'acc-apex-plumbing',
    name: 'Apex Plumbing & Rooter',
    slug: 'apex-plumbing',
    status: 'active',
    plan_tier: 'pro',
    is_demo: true,
    trial_ends_at: new Date(Date.now() + 14 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'acc-coolbreeze-hvac',
    name: 'CoolBreeze Heating & Air',
    slug: 'coolbreeze-hvac',
    status: 'active',
    plan_tier: 'pro',
    is_demo: false,
    trial_ends_at: new Date(Date.now() + 14 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_PROFILES: BusinessProfile[] = [
  {
    id: 'prof-apex-plumbing',
    account_id: 'acc-apex-plumbing',
    business_name: 'Apex Plumbing & Rooter',
    legal_name: 'Apex Plumbing Services LLC',
    trade: 'plumbing',
    ein: '12-3456789',
    address: '1820 E Adams St',
    city: 'Springfield',
    state: 'IL',
    zip: '62704',
    timezone: 'America/Chicago',
    website: 'https://apexplumbingexample.com',
    emergency_phone: '+12175550199',
    notification_phone: '+12175550144',
    carrier_name: 'Verizon Wireless',
    forwarding_configured: true,
    is_demo: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prof-coolbreeze-hvac',
    account_id: 'acc-coolbreeze-hvac',
    business_name: 'CoolBreeze Heating & Air',
    legal_name: 'CoolBreeze Climate Solutions Inc',
    trade: 'hvac',
    ein: '98-7654321',
    address: '450 North Meridian St',
    city: 'Indianapolis',
    state: 'IN',
    zip: '46204',
    timezone: 'America/Indiana/Indianapolis',
    website: 'https://coolbreezeexample.com',
    emergency_phone: '+13175550188',
    notification_phone: '+13175550177',
    carrier_name: 'AT&T Wireless',
    forwarding_configured: true,
    is_demo: false,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_PHONE_NUMBERS: PhoneNumber[] = [
  {
    id: 'phone-apex',
    account_id: 'acc-apex-plumbing',
    phone_number: '+12175550190',
    formatted_number: '+1 (217) 555-0190',
    twilio_sid: 'PN_apex_twilio_sid_1',
    status: 'active',
    capabilities: { voice: true, sms: true, mms: true },
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'phone-coolbreeze',
    account_id: 'acc-coolbreeze-hvac',
    phone_number: '+13175550155',
    formatted_number: '+1 (317) 555-0155',
    twilio_sid: 'PN_coolbreeze_twilio_sid_1',
    status: 'active',
    capabilities: { voice: true, sms: true, mms: true },
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
];

export const SEED_CONTACTS: Contact[] = [
  {
    id: 'cont-john-smith',
    account_id: 'acc-apex-plumbing',
    phone_number: '+12175559821',
    full_name: 'John Smith',
    address: '123 Main Street, Springfield, IL',
    notes: 'Homeowner, emergency water heater burst replacement',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cont-lisa-ray',
    account_id: 'acc-apex-plumbing',
    phone_number: '+12175553312',
    full_name: 'Lisa Ray',
    address: '88 Oak Ridge Ln, Springfield, IL',
    notes: 'Emergency main sewer line backup & hydrojetting',
    created_at: new Date(Date.now() - 3600000 * 8).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cont-robert-chen',
    account_id: 'acc-apex-plumbing',
    phone_number: '+12175557766',
    full_name: 'Robert Chen',
    address: '54 Elm St, Apt 2B, Springfield, IL',
    notes: 'Kitchen sink faucet replacement & supply line check',
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cont-marcus-vance',
    account_id: 'acc-apex-plumbing',
    phone_number: '+12175554421',
    full_name: 'Marcus Vance',
    address: '910 Maple Ave, Springfield, IL',
    notes: 'Sump pump failure - active water rising in basement pit',
    created_at: new Date(Date.now() - 1800000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cont-sarah-jenkins',
    account_id: 'acc-apex-plumbing',
    phone_number: '+12175558123',
    full_name: 'Sarah Jenkins',
    address: '614 S 4th St, Springfield, IL',
    notes: 'Burst copper supply pipe flooding crawlspace',
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cont-amanda-white',
    account_id: 'acc-apex-plumbing',
    phone_number: '+12175554499',
    full_name: 'Amanda White',
    address: '302 Birch Ave, Springfield, IL',
    notes: 'Toilet running non-stop (Self-resolved by customer)',
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cont-unknown-1',
    account_id: 'acc-apex-plumbing',
    phone_number: '+12175556677',
    notes: 'Missed call received 45m ago. Automatic text-back delivered, awaiting customer response.',
    created_at: new Date(Date.now() - 2700000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_JOBS: JobCard[] = [
  {
    id: 'job-101',
    account_id: 'acc-apex-plumbing',
    contact_id: 'cont-john-smith',
    conversation_id: 'conv-john-smith',
    title: 'Water Heater Replacement - Burst Tank',
    trade: 'plumbing',
    problem: '50-gallon tank ruptured in basement, water on floor',
    is_emergency: true,
    address: '123 Main Street, Springfield, IL',
    photo_urls: ['/images/sample-water-heater.jpg'],
    status: 'COMPLETED',
    recovery_source: 'Missed Call — September 27, 2026',
    estimated_value: 1250.0,
    actual_value: 1207.5,
    first_call_time: new Date(Date.now() - 86400000 * 2).toISOString(),
    text_back_time: new Date(Date.now() - 86400000 * 2 + 42000).toISOString(),
    qualified_time: new Date(Date.now() - 86400000 * 2 + 180000).toISOString(),
    contacted_time: new Date(Date.now() - 86400000 * 2 + 600000).toISOString(),
    booked_time: new Date(Date.now() - 86400000 * 1.8).toISOString(),
    completed_time: new Date(Date.now() - 86400000 * 1).toISOString(),
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'job-102',
    account_id: 'acc-apex-plumbing',
    contact_id: 'cont-lisa-ray',
    conversation_id: 'conv-lisa-ray',
    title: 'Emergency Sewer Backup & Hydrojetting',
    trade: 'plumbing',
    problem: 'Raw sewage backing up into basement floor drain and tub - emergency',
    is_emergency: true,
    address: '88 Oak Ridge Ln, Springfield, IL',
    photo_urls: [],
    status: 'BOOKED',
    recovery_source: 'Missed Call — September 29, 2026',
    estimated_value: 650.0,
    actual_value: 650.0,
    first_call_time: new Date(Date.now() - 3600000 * 8).toISOString(),
    text_back_time: new Date(Date.now() - 3600000 * 8 + 8000).toISOString(),
    qualified_time: new Date(Date.now() - 3600000 * 8 + 110000).toISOString(),
    contacted_time: new Date(Date.now() - 3600000 * 8 + 120000).toISOString(),
    booked_time: new Date(Date.now() - 3600000 * 6).toISOString(),
    created_at: new Date(Date.now() - 3600000 * 8).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'job-103',
    account_id: 'acc-apex-plumbing',
    contact_id: 'cont-robert-chen',
    conversation_id: 'conv-robert-chen',
    title: 'Kitchen Faucet Replacement & Supply Lines',
    trade: 'plumbing',
    problem: 'Homeowner purchased Moen fixture, needs installation',
    is_emergency: false,
    address: '54 Elm St, Apt 2B, Springfield, IL',
    photo_urls: [],
    status: 'CONTACTED',
    recovery_source: 'Missed Call — September 29, 2026',
    estimated_value: 320.0,
    first_call_time: new Date(Date.now() - 3600000 * 4).toISOString(),
    text_back_time: new Date(Date.now() - 3600000 * 4 + 40000).toISOString(),
    qualified_time: new Date(Date.now() - 3600000 * 4 + 150000).toISOString(),
    contacted_time: new Date(Date.now() - 3600000 * 2).toISOString(),
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'job-104',
    account_id: 'acc-apex-plumbing',
    contact_id: 'cont-marcus-vance',
    conversation_id: 'conv-marcus-vance',
    title: 'Sump Pump Failure - Basement Flooding',
    trade: 'plumbing',
    problem: 'Sump pump humming but not pumping, water rising in pit',
    is_emergency: true,
    address: '910 Maple Ave, Springfield, IL',
    photo_urls: [],
    status: 'NEW',
    recovery_source: 'Missed Call — September 29, 2026',
    estimated_value: 850.0,
    first_call_time: new Date(Date.now() - 1800000).toISOString(),
    text_back_time: new Date(Date.now() - 1792000).toISOString(),
    qualified_time: new Date(Date.now() - 1500000).toISOString(),
    created_at: new Date(Date.now() - 1800000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'job-106',
    account_id: 'acc-apex-plumbing',
    contact_id: 'cont-sarah-jenkins',
    conversation_id: 'conv-sarah-jenkins',
    title: 'Burst Copper Pipe Emergency Repair',
    trade: 'plumbing',
    problem: 'Burst copper pipe in crawlspace flooding insulation',
    is_emergency: true,
    address: '614 S 4th St, Springfield, IL',
    photo_urls: [],
    status: 'NEW',
    recovery_source: 'Missed Call — September 30, 2026',
    estimated_value: 1300.0,
    first_call_time: new Date(Date.now() - 3600000 * 2).toISOString(),
    text_back_time: new Date(Date.now() - 3600000 * 2 + 8000).toISOString(),
    qualified_time: new Date(Date.now() - 3600000 * 2 + 90000).toISOString(),
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'job-105',
    account_id: 'acc-apex-plumbing',
    contact_id: 'cont-amanda-white',
    title: 'Toilet Flapper Replacement (Self-Resolved)',
    trade: 'plumbing',
    problem: 'Toilet valve sticking',
    is_emergency: false,
    address: '302 Birch Ave, Springfield, IL',
    photo_urls: [],
    status: 'DEAD',
    recovery_source: 'Missed Call — September 25, 2026',
    estimated_value: 150.0,
    notes: 'Customer texted back: my husband fixed it with a new flapper, thank you though!',
    first_call_time: new Date(Date.now() - 86400000 * 4).toISOString(),
    dead_time: new Date(Date.now() - 86400000 * 3.9).toISOString(),
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-lisa-ray',
    account_id: 'acc-apex-plumbing',
    contact_id: 'cont-lisa-ray',
    status: 'active',
    last_message_at: new Date(Date.now() - 3600000 * 7.8).toISOString(),
    created_at: new Date(Date.now() - 3600000 * 8).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'conv-marcus-vance',
    account_id: 'acc-apex-plumbing',
    contact_id: 'cont-marcus-vance',
    status: 'active',
    last_message_at: new Date(Date.now() - 1500000).toISOString(),
    created_at: new Date(Date.now() - 1800000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'conv-sarah-jenkins',
    account_id: 'acc-apex-plumbing',
    contact_id: 'cont-sarah-jenkins',
    status: 'active',
    last_message_at: new Date(Date.now() - 3600000 * 1.9).toISOString(),
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'conv-john-smith',
    account_id: 'acc-apex-plumbing',
    contact_id: 'cont-john-smith',
    status: 'active',
    last_message_at: new Date(Date.now() - 86400000 * 1.9).toISOString(),
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'conv-robert-chen',
    account_id: 'acc-apex-plumbing',
    contact_id: 'cont-robert-chen',
    status: 'active',
    last_message_at: new Date(Date.now() - 3600000 * 3.8).toISOString(),
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_MESSAGES: Message[] = [
  // 1. Lisa Ray - Emergency Timeline with plausible timestamps (Part 3.2)
  {
    id: 'msg-lr-1',
    account_id: 'acc-apex-plumbing',
    conversation_id: 'conv-lisa-ray',
    direction: 'outbound',
    from_number: '+12175550190',
    to_number: '+12175553312',
    body: 'Apex Plumbing & Rooter — sorry we missed your call! Are you contacting us about an active plumbing emergency?',
    media_urls: [],
    status: 'delivered',
    created_at: new Date(Date.now() - 3600000 * 8 + 8000).toISOString(), // 8s after missed call
  },
  {
    id: 'msg-lr-2',
    account_id: 'acc-apex-plumbing',
    conversation_id: 'conv-lisa-ray',
    direction: 'inbound',
    from_number: '+12175553312',
    to_number: '+12175550190',
    body: 'YES EMERGENCY! Raw sewage is backing up into my basement floor drain and tub!',
    media_urls: [],
    status: 'received',
    created_at: new Date(Date.now() - 3600000 * 8 + 53000).toISOString(), // 45s later
  },
  {
    id: 'msg-lr-3',
    account_id: 'acc-apex-plumbing',
    conversation_id: 'conv-lisa-ray',
    direction: 'outbound',
    from_number: '+12175550190',
    to_number: '+12175553312',
    body: 'Understood, treating this as an urgent dispatch! What is your street address?',
    media_urls: [],
    status: 'delivered',
    created_at: new Date(Date.now() - 3600000 * 8 + 60000).toISOString(), // 7s later
  },
  {
    id: 'msg-lr-4',
    account_id: 'acc-apex-plumbing',
    conversation_id: 'conv-lisa-ray',
    direction: 'inbound',
    from_number: '+12175553312',
    to_number: '+12175550190',
    body: '88 Oak Ridge Ln, Springfield. Please hurry, it smells awful!',
    media_urls: [],
    status: 'received',
    created_at: new Date(Date.now() - 3600000 * 8 + 108000).toISOString(), // 48s later
  },
  {
    id: 'msg-lr-5',
    account_id: 'acc-apex-plumbing',
    conversation_id: 'conv-lisa-ray',
    direction: 'outbound',
    from_number: '+12175550190',
    to_number: '+12175553312',
    body: 'Received! Dispatched on-call technician Mike with our heavy hydrojet unit. Confirmed en route, ETA 20 minutes.',
    media_urls: [],
    status: 'delivered',
    created_at: new Date(Date.now() - 3600000 * 8 + 118000).toISOString(), // 10s later
  },

  // 2. Marcus Vance - Sump pump failure
  {
    id: 'msg-m1',
    account_id: 'acc-apex-plumbing',
    conversation_id: 'conv-marcus-vance',
    direction: 'outbound',
    from_number: '+12175550190',
    to_number: '+12175554421',
    body: 'Apex Plumbing & Rooter — sorry we missed your call! Are you contacting us about a plumbing emergency?',
    media_urls: [],
    status: 'delivered',
    created_at: new Date(Date.now() - 1792000).toISOString(), // 8s after missed call
  },
  {
    id: 'msg-m2',
    account_id: 'acc-apex-plumbing',
    conversation_id: 'conv-marcus-vance',
    direction: 'inbound',
    from_number: '+12175554421',
    to_number: '+12175550190',
    body: 'YES EMERGENCY! Sump pump died and rain water is rising in the basement!',
    media_urls: [],
    status: 'received',
    created_at: new Date(Date.now() - 1650000).toISOString(),
  },
  {
    id: 'msg-m3',
    account_id: 'acc-apex-plumbing',
    conversation_id: 'conv-marcus-vance',
    direction: 'outbound',
    from_number: '+12175550190',
    to_number: '+12175554421',
    body: 'Understood, prioritizing this right now. What is your service address?',
    media_urls: [],
    status: 'delivered',
    created_at: new Date(Date.now() - 1620000).toISOString(),
  },
  {
    id: 'msg-m4',
    account_id: 'acc-apex-plumbing',
    conversation_id: 'conv-marcus-vance',
    direction: 'inbound',
    from_number: '+12175554421',
    to_number: '+12175550190',
    body: '910 Maple Ave here in Springfield. Please hurry!',
    media_urls: [],
    status: 'received',
    created_at: new Date(Date.now() - 1500000).toISOString(),
  },

  // 3. Sarah Jenkins - Burst Copper Pipe
  {
    id: 'msg-sj-1',
    account_id: 'acc-apex-plumbing',
    conversation_id: 'conv-sarah-jenkins',
    direction: 'outbound',
    from_number: '+12175550190',
    to_number: '+12175558123',
    body: 'Apex Plumbing & Rooter — sorry we missed your call! Are you contacting us about a plumbing emergency?',
    media_urls: [],
    status: 'delivered',
    created_at: new Date(Date.now() - 3600000 * 2 + 8000).toISOString(),
  },
  {
    id: 'msg-sj-2',
    account_id: 'acc-apex-plumbing',
    conversation_id: 'conv-sarah-jenkins',
    direction: 'inbound',
    from_number: '+12175558123',
    to_number: '+12175550190',
    body: 'Yes, emergency burst pipe in crawlspace spraying water under my floorboards!',
    media_urls: [],
    status: 'received',
    created_at: new Date(Date.now() - 3600000 * 2 + 45000).toISOString(),
  },
  {
    id: 'msg-sj-3',
    account_id: 'acc-apex-plumbing',
    conversation_id: 'conv-sarah-jenkins',
    direction: 'outbound',
    from_number: '+12175550190',
    to_number: '+12175558123',
    body: 'Shut off your main valve immediately if you can access it safely. What is your address?',
    media_urls: [],
    status: 'delivered',
    created_at: new Date(Date.now() - 3600000 * 2 + 52000).toISOString(),
  },
  {
    id: 'msg-sj-4',
    account_id: 'acc-apex-plumbing',
    conversation_id: 'conv-sarah-jenkins',
    direction: 'inbound',
    from_number: '+12175558123',
    to_number: '+12175550190',
    body: 'Valve shut off! Address is 614 S 4th St, Springfield.',
    media_urls: [],
    status: 'received',
    created_at: new Date(Date.now() - 3600000 * 2 + 90000).toISOString(),
  },

  // 4. John Smith - Water heater replacement
  {
    id: 'msg-1',
    account_id: 'acc-apex-plumbing',
    conversation_id: 'conv-john-smith',
    direction: 'outbound',
    from_number: '+12175550190',
    to_number: '+12175559821',
    body: 'Apex Plumbing & Rooter — sorry we missed your call! Are you contacting us about a plumbing emergency?',
    media_urls: [],
    status: 'delivered',
    created_at: new Date(Date.now() - 86400000 * 2 + 42000).toISOString(),
  },
  {
    id: 'msg-2',
    account_id: 'acc-apex-plumbing',
    conversation_id: 'conv-john-smith',
    direction: 'inbound',
    from_number: '+12175559821',
    to_number: '+12175550190',
    body: 'YES! My water heater in the basement is leaking everywhere!',
    media_urls: [],
    status: 'received',
    created_at: new Date(Date.now() - 86400000 * 2 + 85000).toISOString(),
  },
  {
    id: 'msg-3',
    account_id: 'acc-apex-plumbing',
    conversation_id: 'conv-john-smith',
    direction: 'outbound',
    from_number: '+12175550190',
    to_number: '+12175559821',
    body: 'Understood. We treat this as an emergency. What is the service address where you need help?',
    media_urls: [],
    status: 'delivered',
    created_at: new Date(Date.now() - 86400000 * 2 + 95000).toISOString(),
  },
  {
    id: 'msg-4',
    account_id: 'acc-apex-plumbing',
    conversation_id: 'conv-john-smith',
    direction: 'inbound',
    from_number: '+12175559821',
    to_number: '+12175550190',
    body: '123 Main Street here in Springfield',
    media_urls: [],
    status: 'received',
    created_at: new Date(Date.now() - 86400000 * 2 + 140000).toISOString(),
  },
  {
    id: 'msg-5',
    account_id: 'acc-apex-plumbing',
    conversation_id: 'conv-john-smith',
    direction: 'outbound',
    from_number: '+12175550190',
    to_number: '+12175559821',
    body: 'Got it. We dispatched technician Mike. He confirmed parts and ETA is 25 minutes.',
    media_urls: [],
    status: 'delivered',
    created_at: new Date(Date.now() - 86400000 * 2 + 180000).toISOString(),
  },

  // 5. Robert Chen - Faucet replacement
  {
    id: 'msg-rc-1',
    account_id: 'acc-apex-plumbing',
    conversation_id: 'conv-robert-chen',
    direction: 'outbound',
    from_number: '+12175550190',
    to_number: '+12175557766',
    body: 'Apex Plumbing & Rooter — sorry we missed your call! How can we help you today?',
    media_urls: [],
    status: 'delivered',
    created_at: new Date(Date.now() - 3600000 * 4 + 40000).toISOString(),
  },
  {
    id: 'msg-rc-2',
    account_id: 'acc-apex-plumbing',
    conversation_id: 'conv-robert-chen',
    direction: 'inbound',
    from_number: '+12175557766',
    to_number: '+12175550190',
    body: 'Hi, I need a new kitchen sink faucet installed and my shutoff valves inspected.',
    media_urls: [],
    status: 'received',
    created_at: new Date(Date.now() - 3600000 * 4 + 95000).toISOString(),
  },
  {
    id: 'msg-rc-3',
    account_id: 'acc-apex-plumbing',
    conversation_id: 'conv-robert-chen',
    direction: 'outbound',
    from_number: '+12175550190',
    to_number: '+12175557766',
    body: 'We can certainly take care of that. What is your address and preferred appointment window?',
    media_urls: [],
    status: 'delivered',
    created_at: new Date(Date.now() - 3600000 * 4 + 115000).toISOString(),
  },
  {
    id: 'msg-rc-4',
    account_id: 'acc-apex-plumbing',
    conversation_id: 'conv-robert-chen',
    direction: 'inbound',
    from_number: '+12175557766',
    to_number: '+12175550190',
    body: '54 Elm St, Apt 2B in Springfield. Tomorrow afternoon between 1 PM and 3 PM would be great.',
    media_urls: [],
    status: 'received',
    created_at: new Date(Date.now() - 3600000 * 4 + 150000).toISOString(),
  },
];

export const SEED_CALL_RECORDS: CallRecord[] = [
  {
    id: 'call-104',
    account_id: 'acc-apex-plumbing',
    twilio_call_sid: 'CA_sample_call_104',
    from_number: '+12175554421',
    to_number: '+12175550190',
    direction: 'inbound',
    start_time: new Date(Date.now() - 1800000).toISOString(),
    end_time: new Date(Date.now() - 1800000 + 19000).toISOString(),
    duration: 19,
    call_status: 'no-answer',
    missed_reason: 'no-answer',
    forwarded_status: 'conditionally-forwarded',
    text_back_status: 'sent',
    deduplication_state: 'first_call',
    created_at: new Date(Date.now() - 1800000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'call-107',
    account_id: 'acc-apex-plumbing',
    twilio_call_sid: 'CA_sample_call_107',
    from_number: '+12175558123',
    to_number: '+12175550190',
    direction: 'inbound',
    start_time: new Date(Date.now() - 3600000 * 2).toISOString(),
    end_time: new Date(Date.now() - 3600000 * 2 + 25000).toISOString(),
    duration: 25,
    call_status: 'no-answer',
    missed_reason: 'no-answer',
    forwarded_status: 'conditionally-forwarded',
    text_back_status: 'sent',
    deduplication_state: 'first_call',
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'call-106',
    account_id: 'acc-apex-plumbing',
    twilio_call_sid: 'CA_sample_call_106',
    from_number: '+12175556677',
    to_number: '+12175550190',
    direction: 'inbound',
    start_time: new Date(Date.now() - 2700000).toISOString(),
    end_time: new Date(Date.now() - 2700000 + 14000).toISOString(),
    duration: 14,
    call_status: 'no-answer',
    missed_reason: 'no-answer',
    forwarded_status: 'conditionally-forwarded',
    text_back_status: 'sent',
    deduplication_state: 'first_call',
    created_at: new Date(Date.now() - 2700000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'call-103',
    account_id: 'acc-apex-plumbing',
    twilio_call_sid: 'CA_sample_call_103',
    from_number: '+12175557766',
    to_number: '+12175550190',
    direction: 'inbound',
    start_time: new Date(Date.now() - 3600000 * 4).toISOString(),
    end_time: new Date(Date.now() - 3600000 * 4 + 15000).toISOString(),
    duration: 15,
    call_status: 'no-answer',
    missed_reason: 'busy',
    forwarded_status: 'conditionally-forwarded',
    text_back_status: 'sent',
    deduplication_state: 'first_call',
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'call-102',
    account_id: 'acc-apex-plumbing',
    twilio_call_sid: 'CA_sample_call_102',
    from_number: '+12175553312',
    to_number: '+12175550190',
    direction: 'inbound',
    start_time: new Date(Date.now() - 3600000 * 8).toISOString(),
    end_time: new Date(Date.now() - 3600000 * 8 + 22000).toISOString(),
    duration: 22,
    call_status: 'busy',
    missed_reason: 'busy',
    forwarded_status: 'conditionally-forwarded',
    text_back_status: 'sent',
    deduplication_state: 'first_call',
    created_at: new Date(Date.now() - 3600000 * 8).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'call-101',
    account_id: 'acc-apex-plumbing',
    twilio_call_sid: 'CA_sample_call_101',
    from_number: '+12175559821',
    to_number: '+12175550190',
    direction: 'inbound',
    start_time: new Date(Date.now() - 86400000 * 2).toISOString(),
    end_time: new Date(Date.now() - 86400000 * 2 + 18000).toISOString(),
    duration: 18,
    call_status: 'no-answer',
    missed_reason: 'no-answer',
    forwarded_status: 'conditionally-forwarded',
    text_back_status: 'sent',
    deduplication_state: 'first_call',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'call-105',
    account_id: 'acc-apex-plumbing',
    twilio_call_sid: 'CA_sample_call_105',
    from_number: '+12175554499',
    to_number: '+12175550190',
    direction: 'inbound',
    start_time: new Date(Date.now() - 86400000 * 4).toISOString(),
    end_time: new Date(Date.now() - 86400000 * 4 + 20000).toISOString(),
    duration: 20,
    call_status: 'no-answer',
    missed_reason: 'after-hours',
    forwarded_status: 'conditionally-forwarded',
    text_back_status: 'sent',
    deduplication_state: 'first_call',
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Part 3.8: Explicit gap analysis test calls
  {
    id: 'call-108-dedupe',
    account_id: 'acc-apex-plumbing',
    twilio_call_sid: 'CA_sample_call_108',
    from_number: '+12175554421', // Marcus Vance calling again 15m later
    to_number: '+12175550190',
    direction: 'inbound',
    start_time: new Date(Date.now() - 900000).toISOString(),
    end_time: new Date(Date.now() - 900000 + 10000).toISOString(),
    duration: 10,
    call_status: 'no-answer',
    missed_reason: 'no-answer',
    forwarded_status: 'conditionally-forwarded',
    text_back_status: 'deduplicated',
    deduplication_state: 'duplicate_suppressed',
    created_at: new Date(Date.now() - 900000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'call-109-optout',
    account_id: 'acc-apex-plumbing',
    twilio_call_sid: 'CA_sample_call_109',
    from_number: '+12175559988',
    to_number: '+12175550190',
    direction: 'inbound',
    start_time: new Date(Date.now() - 3600000 * 5).toISOString(),
    end_time: new Date(Date.now() - 3600000 * 5 + 12000).toISOString(),
    duration: 12,
    call_status: 'no-answer',
    missed_reason: 'no-answer',
    forwarded_status: 'conditionally-forwarded',
    text_back_status: 'suppressed',
    deduplication_state: 'first_call',
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'call-110-quiethours',
    account_id: 'acc-apex-plumbing',
    twilio_call_sid: 'CA_sample_call_110',
    from_number: '+12175551122',
    to_number: '+12175550190',
    direction: 'inbound',
    start_time: new Date(Date.now() - 3600000 * 12).toISOString(), // late night
    end_time: new Date(Date.now() - 3600000 * 12 + 15000).toISOString(),
    duration: 15,
    call_status: 'no-answer',
    missed_reason: 'after-hours',
    forwarded_status: 'conditionally-forwarded',
    text_back_status: 'pending',
    deduplication_state: 'first_call',
    created_at: new Date(Date.now() - 3600000 * 12).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_COMPLIANCE: ComplianceRegistration[] = [
  {
    id: 'comp-apex',
    account_id: 'acc-apex-plumbing',
    legal_name: 'Apex Plumbing Services LLC',
    ein: '12-3456789',
    business_type: 'LLC',
    address: '1820 E Adams St, Springfield, IL 62704',
    website: 'https://apexplumbingexample.com',
    contact_name: 'Apex Owner',
    contact_email: 'support@apexplumbingexample.com',
    contact_phone: '+12175550144',
    brand_sid: null,
    campaign_sid: null,
    status: 'signed_up',
    carrier_source: 'demo',
    sample_messages: [
      'Apex Plumbing & Rooter — sorry we missed your call! Are you contacting us about a plumbing emergency?',
      'Thanks for the details! We have dispatched a technician.',
    ],
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'comp-coolbreeze',
    account_id: 'acc-coolbreeze-hvac',
    legal_name: 'CoolBreeze Climate Solutions Inc',
    ein: '98-7654321',
    business_type: 'Corporation',
    address: '450 North Meridian St, Indianapolis, IN 46204',
    website: 'https://coolbreezeexample.com',
    contact_name: 'Sarah Jenkins',
    contact_email: 'sarah@coolbreezeexample.com',
    contact_phone: '+13175550177',
    brand_sid: null,
    campaign_sid: null,
    status: 'signed_up',
    carrier_source: 'demo',
    sample_messages: [
      'CoolBreeze Heating & Air — sorry we missed your call! Is your heating or cooling system completely down?',
    ],
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    account_id: 'acc-apex-plumbing',
    title: '🚨 Emergency Job Created',
    body: 'John Smith reported a bursting water heater at 123 Main Street. Action required immediately.',
    type: 'emergency',
    is_read: false,
    metadata: { jobId: 'job-101', contactId: 'cont-john-smith' },
    created_at: new Date(Date.now() - 3600000 * 2.9).toISOString(),
  },
  {
    id: 'notif-2',
    account_id: 'acc-apex-plumbing',
    title: 'Missed Call Recovered via SMS',
    body: 'Lisa Ray responded to missed-call text-back. Sewer drain issue qualified.',
    type: 'qualified_job',
    is_read: true,
    metadata: { jobId: 'job-102', contactId: 'cont-lisa-ray' },
    created_at: new Date(Date.now() - 3600000 * 7.8).toISOString(),
  },
];

export const SEED_CANNED_REPLIES: CannedReply[] = [
  ...TRADE_TEMPLATES.plumbing.canned_replies.map((cr, idx) => ({
    id: `canned-apex-${idx}`,
    account_id: 'acc-apex-plumbing',
    title: cr.title,
    shortcut: cr.shortcut,
    body: cr.body,
    trade: 'plumbing' as const,
    is_default: idx === 0,
    created_at: new Date().toISOString(),
  })),
];

export const SEED_USAGE: UsageRecord[] = [
  {
    id: 'use-apex-current',
    account_id: 'acc-apex-plumbing',
    period_start: new Date(Date.now() - 15 * 86400000).toISOString(),
    period_end: new Date(Date.now() + 15 * 86400000).toISOString(),
    calls_count: 68,
    sms_count: 312,
    mms_count: 14,
    numbers_count: 1,
    overage_amount_cents: 0,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
];

export const SEED_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 'sub-apex',
    account_id: 'acc-apex-plumbing',
    plan_id: 'pro',
    stripe_customer_id: undefined,
    stripe_subscription_id: undefined,
    status: 'active',
    current_period_start: new Date(Date.now() - 15 * 86400000).toISOString(),
    current_period_end: new Date(Date.now() + 15 * 86400000).toISOString(),
    cancel_at_period_end: false,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_USER_CREDENTIALS: UserCredential[] = [
  {
    id: 'cred-apex-demo',
    user_id: 'usr-demo-owner',
    account_id: 'acc-apex-plumbing',
    email: 'demo@apexplumbing.com',
    password_hash: hashPasswordSync('ApexDemo2026!Secure', 'a1b2c3d4e5f60718'),
    algorithm: 'scrypt',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cred-coolbreeze',
    user_id: 'usr-coolbreeze-owner',
    account_id: 'acc-coolbreeze-hvac',
    email: 'owner@coolbreezehvac.com',
    password_hash: hashPasswordSync('CoolBreeze2026!Secure', 'b2c3d4e5f6a10719'),
    algorithm: 'scrypt',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

